name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-check:
    name: runner / terraform validate (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info
          workdir: ./testdata/

  test-check-with-opentofu:
    name: runner / tofu validate (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info
          workdir: ./testdata/
          terraform_version: "1.8.8"
          cli: "opentofu"

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / terraform validate (github-pr-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
          workdir: ./testdata/

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / terraform validate (github-pr-review)
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          reviewdog_flags: -filter-mode=file -fail-on-error
          workdir: ./testdata/
